@startuml get_room_cloud_workflow
footer  Hosts Guru\n  [[https://github.com/hosts-guru/documentation Hosts Guru Docs]]

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v10.0/dist
!includeurl AWSPuml/AWSSimplified.puml
!includeurl AWSPuml/General/User.puml
!includeurl AWSPuml/Containers/EKSCloud.puml
!includeurl AWSPuml/Database/DynamoDB.puml
!includeurl AWSPuml/SecurityIdentityCompliance/Cognito.puml

skinparam {
    DefaultTextAlignment center
    SequenceMessageAlign first
    backgroundColor #EEEBDC
    BorderColor AWS_BORDER_COLOR
}

left to right direction

Cognito(cognitoAuthorization, "Cognito Auth", "")
EKSCloud(roomMicrosservice, "Rooms Microsservice", "")
User(hotelUser, "Hotel Administrator", "")
DynamoDB(roomsDynamoDB, "Rooms Database", "")


hotelUser <-->roomMicrosservice: Send Payload to Get One Room or Many Rooms
hotelUser<-->cognitoAuthorization: Request Access
roomMicrosservice <-->roomsDynamoDB: Get Room into Rooms Database

@enduml