name: generate plantuml
on:
  pull_request:
    paths:
      - '**.puml'
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install -y graphviz plantuml
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Process Diagrams
        run: plantuml -v -tsvg -r -o "./" "${{ github.workspace }}/**.puml"
      - name: Commit Diagrams
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m ":rocket: adding generated diagrams" || exit 0
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push Diagrams
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}